



#### Exercício - Subespaço Gerado

Seja $W$ o subespaço de $M_{3\times2}(\mathbb{R})$ gerado pelas matrizes

$$A_1 = \begin{bmatrix} 0 & 0 \\ 1 & 1 \\ 0 & 0 \end{bmatrix} , \;
A_2 = \begin{bmatrix} 0 & 1 \\ 0 & -1 \\ 1 & 0 \end{bmatrix} \; \text{e} \;
A_3 = \begin{bmatrix} 0 & 1 \\ 0 & 0 \\ 0 & 0 \end{bmatrix} .$$

Implemente um código para verificar se a matriz $$A = \begin{bmatrix} 0 & 2 \\ 3 & 4 \\ 5 & 0 \end{bmatrix}$$ pertence ao subespaço $W$.

In [9]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip


In [10]:
import numpy as np

# Declarando as matrizes
A1 = np.array([[0, 0], [1, 1], [0, 0]])
A2 = np.array([[0, 1], [0, -1], [1, 0]])
A3 = np.array([[0, 1], [0, 0], [0, 0]])
A = np.array([[0, 2], [3, 4], [5, 0]])

A.flatten()

array([0, 2, 3, 4, 5, 0])

In [11]:
# Criando a matriz de coeficientes
M = np.column_stack([A1.flatten(), A2.flatten(), A3.flatten()])
M

array([[ 0,  0,  0],
       [ 0,  1,  1],
       [ 1,  0,  0],
       [ 1, -1,  0],
       [ 0,  1,  0],
       [ 0,  0,  0]])

In [12]:
# Resolvendo o sistema
coeficientes, residuo, _, _ = np.linalg.lstsq(M, A.flatten())

coeficientes, residuo

(array([ 5.,  3., -1.]), array([12.]))

In [13]:
# Vendo se ela pertence ao subespaço
if np.allclose(M @ coeficientes, A.flatten()):
    print("ESTA SIM")
else:
    print("NAO TA NAO")

NAO TA NAO
